name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:   
  push:
    branches: ['master']
  workflow_dispatch:  
jobs:

  BuildImage-and-PushToACR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
    
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'githubworkflow'
          # Container registry password
          password: 'rPvPS8ldsFJyj5dvkR+BVDR/FMlCl1Xe3ilBS6PYPZ+ACRDiDtyl'
          # Container registry server url
          login-server: 'githubworkflow.azurecr.io'
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
         push: true
         tags: githubworkflow.azurecr.io/hello-world-app:${{ github.sha }}
         file: ./Dockerfile
      

  
  Deploy-To-K8s:
    runs-on: ubuntu-latest
    steps:
      - run: echo ""
    
