name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:   
  push:
    branches: ['master']
  workflow_dispatch:  

permissions:
  contents: read

jobs:

  BuildImage-and-PushToACR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
    
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'githubworkflow'
          # Container registry password
          password: 'rPvPS8ldsFJyj5dvkR+BVDR/FMlCl1Xe3ilBS6PYPZ+ACRDiDtyl'
          # Container registry server url
          login-server: 'githubworkflow.azurecr.io'
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
         push: true
         tags: githubworkflow.azurecr.io/hello-world-app:${{ github.sha }}
         file: ./Dockerfile
      

  
  Deploy-To-AzureK8s:
    permissions: 
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [BuildImage-and-PushToACR]
    environment: Production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: 'c43801b5-0c3b-433f-a4ee-bf9c633f5632'
          tenant-id: '82cb0d5a-f537-44bc-9927-f4a6b3456d9e'
          subscription-id: '790b1e5c-2be9-4fc0-b83d-ef829ea097d7'
    
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'jenkins-rg'
          # AKS Cluster Name
          cluster-name: 'hellowplrdK8s'
          # AKS Cluster Subscription
          subscription: '790b1e5c-2be9-4fc0-b83d-ef829ea097d7'
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
      - name: Deploy applications
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            kubernetes/hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            githubworkflow.azurecr.io/hello-world-app:${{ github.sha }}
            

    
