name: Build and Deploy to Azure Env
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

env:
  AZURE_CONTAINER_REGISTRY_SERVER: 'githubworkflow.azurecr.io'
on:   
  push:
    branches: ['master']
  workflow_dispatch:  

permissions:
  contents: read

jobs:

  BuildImage-and-PushToACR:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 
    
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: 'githubworkflow'
          # Container registry password
          password: ${{ secrets.CONTAINER_RAGISTRY_PASSWORD }}
          # Container registry server url
          login-server: ${{ env.AZURE_CONTAINER_REGISTRY_SERVER }}
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
         push: true
         tags: githubworkflow.azurecr.io/hello-world-app:${{ github.sha }}
         file: ./Dockerfile
      

  
  Deploy-To-AzureK8s:
    permissions: 
      actions: read
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    needs: [BuildImage-and-PushToACR]
    environment: Production
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
      - name: Setup kubelogin
        uses: Azure/use-kubelogin@v1
        with:
            kubelogin-version: 'v0.0.25'
        
      - name: Azure Kubernetes set context
        uses: Azure/aks-set-context@v3
        with:
          # Resource Group Name
          resource-group: 'jenkins-rg'
          # AKS Cluster Name
          cluster-name: 'hellowplrdK8s'
          # AKS Cluster Subscription
          subscription: '790b1e5c-2be9-4fc0-b83d-ef829ea097d7'
          # Get cluster admin credentials. Values: true or false
          admin: 'false'
          # Enables kubelogin for non-admin user scenario. Values: true or false
          use-kubelogin: 'true'
          
      - name: Substitute environment variables   
        uses: danielr1996/envsubst-action@1.1.0
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          AZURE_CONTAINER_REGISTRY: githubworkflow.azurecr.io
          CONTAINER_NAME: hello-world-app:${{ github.sha }}
        with:
          input:
            kubernetes/hello-world-deployment.yaml
          output:
            hello-world-deployment.yaml
          
      - name: Deploy applications
        uses: Azure/k8s-deploy@v4
        with:
          action: deploy
          manifests: |
            hello-world-deployment.yaml
            kubernetes/hello-world-service.yaml
          images: |
            githubworkflow.azurecr.io/hello-world-app:${{ github.sha }}
            

    
